### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by voltflake** [DrexHD/AntiXray#12]
Can you add compile instructions to README.md or set up automatic builds?
I never compiled minecraft mod or any java project before and I need jar for 1.18 version for my server.

**Comment by DrexHD** [comment]
There are automatic builds over at [Github Actions](https://github.com/DrexHD/AntiXray/actions). ;)

**Comment by voltflake** [comment]
Artifacts still aren't available to download :/

**Comment by DrexHD** [comment]
Should be available now.
