### ISSUE TITLE
Chunks are not properly sent to clients

### ISSUE THREAD

**Issue by DomiIRL** [DrexHD/AntiXray#13]
I've had the problem that with the 1.18 experimental build installed that some chunks wouldn't be loaded for some players.
Some players just couldn't see some chunks and only a rejoin or waiting for a long time could fix that for a short time.

**Comment by DrexHD** [comment]
Hey, please send your config and any errors in the console. In case you are using engine mode 2, I need to inform you that it is not currently supported because it is very unstable.

- Drex

**Comment by DomiIRL** [comment]
Error: https://sourceb.in/31FYVQGDun
The config ist just the default one: https://sourceb.in/b7XYInX6Ee

**Comment by DrexHD** [comment]
As I have mentioned in my previous comment, engine mode 2 is currently unstable. Please grab the latest release from modrinth / curseforge that force-disables that option or change engine mode 2 to engine mode 1 in your config.

**Comment by DomiIRL** [comment]
Okay I'm gonna test it with it disabled thanks
