### ISSUE TITLE
Poor performance when generating a lot of chunks

### ISSUE THREAD

**Issue by Londiuh** [DrexHD/AntiXray#18]
When a player is generating a lot of chunks very fast (tested using elytra + rockets), the server lags a lot and the console gets spammed with `Can't keep up! Is the server overloaded?` and `moved too quickly!`

**Comment by DrexHD** [comment]
This isn't enough information for me. What you describe can also be observed in vanilla. If you want to report performance issues, please run a profiler (eg. [spark](https://spark.lucko.me/download)) and post the result here.

**Comment by Londiuh** [comment]
Mods:
- c2me
- fabric-api
- krypton
- lithium
- spark
- starlight

Generating a lot of chunks:
Without AntiXray: https://spark.lucko.me/PMGSKfbPFL
With AntiXray: https://spark.lucko.me/EEY76HGvPY

**Comment by DrexHD** [comment]
Thanks. Please make sure `noTickViewDistance` in c2me config is disabled. If you can still replicate the behaviour, please share the c2me and antixray config, so I can try to reproduce this.

**Comment by Londiuh** [comment]
> Thanks. Please make sure `noTickViewDistance` in c2me config is disabled. If you can still replicate the behaviour, please share the c2me and antixray config, so I can try to reproduce this.

Yes, `noTickViewDistance` is disabled. I'm using default config for both.

**Comment by DrexHD** [comment]
`noTickViewDistance` is set to some compatability mode by default. I don't yet know why that increases the load of antixray so much, but disabling `noTickViewDistance` by setting `enabled` to false, seems to resolve that.

**Comment by Londiuh** [comment]
Oh, I thought `noTickViewDistance` was disabled by default. I disabled it and now the TPS are fine when generating new chunks. I'll use 1.18 simulation distance instead.
