### ISSUE TITLE
[REQUEST] 1.16.5 Forge port, reasons below

### ISSUE THREAD

**Issue by Sunconure11** [DrexHD/AntiXray#19]
Recently my Crucial 2 server got hit by some nasty trolls, and we suspect some of them were x-raying. However, this mod does not exist for 1.16.5, which is what Crucial 2 is on. Could this be ported to such a version? If not, can you show me a similar mod to this on 1.16.5?

**Comment by DrexHD** [comment]
Someone already asked this on curseforge
> I currently don't have the time nor the motivation to backport this mod to 1.16.5.

It also seems that mixins (which are used by this mod) have been added to fabric in 1.17, so they aren't even avaible for the requested version.

I am sadly not aware of any similar mods.

- Drex
