### ISSUE TITLE
 Question

### ISSUE THREAD

**Issue by Nakijama** [DrexHD/AntiXray#20]
Hello

Tell me friend if it is possible to add ore from other mods. I have been sitting on it since the morning and I do not understand it and I would like to add them because I do not trust my friends with children and we want to play together. In fact, I'm not a technique and I do everything on tutorials.

I wrote in hiding ores, ores from immersive but I still show them to me and we only have this mod with additional ores and the rest are just libraries or some simplifications

Regards.

**Comment by DrexHD** [comment]
Hello

I don't know what mod you are referring to, but when adding the block id's you need to make sure to use the full id (The block id you can see in F3 Menu when looking at the block, for example: `testmod:aluminum_ore`) for any non vanilla blocks. If this doesn't work, make sure to attach your config.

Drex

**Comment by Nakijama** [comment]
<a href="https://imgur.com/P14nuLG"><img src="https://i.imgur.com/P14nuLG.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/XO2s0bL"><img src="https://i.imgur.com/XO2s0bL.png" title="source: imgur.com" /></a>

Hello

Let me tell you that I tried in different ways but I do not hide them.
And I mean the immersive engineering mod, I even wrote (ore_aluminum) as it writes under F3. I did various combinations. Vanilla ore hides perfectly.

Regards

**Comment by DrexHD** [comment]
Hello

I have just done some testing and `"immersiveengineering:ore_aluminum"` should work to hide for example immersives alluminum ore.

Drex

**Comment by Nakijama** [comment]
> Hello
> 
> I have just done some testing and `"immersiveengineering:ore_aluminum"` should work to hide for example immersives alluminum ore.
> 
> Drex

Hello

Thank you, everything works, but only after I copied your post with the ore ;][

**Comment by Nakijama** [comment]
``````````````````````````````````````````````````````
