### ISSUE TITLE
Some changes to config file do not apply

### ISSUE THREAD

**Issue by wwawaawwa** [DrexHD/AntiXray#21]
In version 1.2.2 for 1.19 as far as I have tested, changes to the `hiddenBlocks` and `replacmentBlocks` options in the overworld section are not applied and the default values are still used.

I have not tested this extensively and there may be more options that are affected.

My current config file:
```
# Default configuration file for Fabric AntiXray mod by DrexHD

# Default values
enabled = false

# World specific values
[overworld]
enabled = true
engineMode = 1
maxBlockHeight = 256
updateRadius = 2
lavaObscures = true
hiddenBlocks = ["copper_ore", "deepslate_copper_ore", "raw_copper_block", "gold_ore", "deepslate_gold_ore", "raw_gold_block", "iron_ore", "deepslate_iron_ore", "raw_iron_block", "coal_ore", "deepslate_coal_ore", "lapis_ore", "deepslate_lapis_ore", "mossy_cobblestone", "obsidian", "chest", "diamond_ore", "deepslate_diamond_ore", "redstone_ore", "deepslate_redstone_ore", "clay", "emerald_ore", "deepslate_emerald_ore", "ender_chest", "deepslate", "stone"]
replacementBlocks = ["deepslate_emerald_ore"]

[the_nether]
enabled = true
engineMode = 1
maxBlockHeight = 128
updateRadius = 2
lavaObscures = true
hiddenBlocks = ["ancient_debris", "nether_quartz_ore", "nether_gold_ore"]
replacementBlocks = ["netherrack"]
```

**Comment by DrexHD** [comment]
The config is very similar to Paper's Antixray config, which is documented at https://docs.papermc.io/paper/anti-xray. The config value names are indeed missleading and confusing without documentation. If I ever rewrite this mod I will do something about the confusing config.

Kind regards,
Drex
