### ISSUE TITLE
Mod doesn't create config file in singleplayer

### ISSUE THREAD

**Issue by ghost** [DrexHD/AntiXray#23]
As the title says, but I don't know if this is intended. I usually set up my servers in single player first, as it is easier to do all the configs there, and then copy them to the server. 

Thanks for this amazing port!

Kind regards,
Tia

**Comment by DrexHD** [comment]
The mod works by manipulating packets sent from the server to the client and therefor only works if installed on a server.

Kind regards,
Drex
