### ISSUE TITLE
Certain players constantly time out and are unable to play

### ISSUE THREAD

**Issue by zischknall** [DrexHD/AntiXray#26]
Installed the mod to prevent players from xraying.

Got complains from a friend that they are unable to play and loose connection every two minutes.
In the console I could see that they are timing out constantly. After an internet search I came across the info that the paper anti-xray patch, which this mod is based on can mess with keep-alive packets. Which in turn can lead to players timing out.

Is there any way to prevent the issue from happening or fixing it?

**Comment by DrexHD** [comment]
Engine mode 2 can cause players with slower connection to time out. You could change engine mode to 1, which doesn't have that problem. I am also currently experimenting with a bypass permission (a2631caf927bbaebb907d2ca33a22f5cf618e419), so you can disable antixray for people you trust. I am also currently testing another idea to improve the compression of engine mode 2 (d3f1db20580ef74b4995a62575b6c0252c314afd)

**Comment by zischknall** [comment]
Thanks a lot for your answer and effort.
I was using the TimeOutOut mod before, which also seemed to fix it.

For now I removed it and the old version again and trialing the experimental fix. Will report back here after the offending player was online.

**Comment by zischknall** [comment]
Player hasn't been online yet so no conclusive answer. Otherwise I noticed that the default engine mode `1` for nether does not seem to work. I don't know how it was with the other version as we just activated the nether on our server.

Changing to engine mode `2` seems to work though.
