### ISSUE TITLE
Crash on 1.19.2, possibly very-many-players related

### ISSUE THREAD

**Issue by MattiDragon** [DrexHD/AntiXray#28]
My server seems to be randomly crashing due to this mod. It seems like you expect the chunk to be set, but it isn't in `ClientboundLevelChunkWithLightPacketMixin` for some reason. Might be vmp related

Here's the crash log:
[crash-2022-12-18_10.07.38-server.txt](https://github.com/DrexHD/AntiXray/files/10253590/crash-2022-12-18_10.07.38-server.txt)

**Comment by DrexHD** [comment]
I am aware of this issue and already working on a fix (until this is fixed you can use version 1.2.6, which doesn't have this issue)
