### ISSUE TITLE
The ability to add blocks that don't obscure.

### ISSUE THREAD

**Issue by goosewoman** [DrexHD/AntiXray#31]
Currently when I'm playing a modded pack some modded blocks with transparency (like [quark crystals](https://www.curseforge.com/minecraft/mc-mods/quark-crystals)) I can see the obfuscation after it. Because these blocks "obscure". 

I don't think there's an easy way to catch all types of transparent blocks from every mod, but I think it's a good idea to add a config value to add block tags or individual blocks that shouldn't obscure, so that I can ensure there's not a mess of obfuscation behind these modded blocks.

**Comment by DrexHD** [comment]
This is already a feature.
> `hiddenBlocks` a list of blocks to hide *(Engine mode 1)* or a list of blocks to use for obfuscation *(Engine mode 2/3)*
`replacementBlocks` is a list of blocks that will be obfuscated, but not used as fake blocks *(Engine mode 2/3 only)*

By default AntiXray will use the block tag `#c:ores` in `hiddenBlocks`. If you have special ore blocks that shouldn't be used for obfuscation you should manually add all blocks that *should* be used for obfuscation to `hiddenBlocks` and remove `c#ores` (or `#forge:ores` on forge). You can then add all blocks that should be hidden, but not used for obfuscation to the `replacementBlocks` list.
