### ISSUE TITLE
Changes to the config file does not apply

### ISSUE THREAD

**Issue by splyfof** [DrexHD/AntiXray#32]
I have changed the config update radius without it having a effect on the game.

This was mentioned in #21 which i believe shouldn't have been closed as changes to the config file doesn't always apply to the world.
![chrome_NqbqRrzp8Y](https://github.com/DrexHD/AntiXray/assets/83120236/a36a5a81-4297-4ff9-96dc-c0fb1a15a0e1)
![java_Mjf6untvaD](https://github.com/DrexHD/AntiXray/assets/83120236/acefc1d2-3f65-4d55-9b58-054a31eaea2f)

**Comment by DrexHD** [comment]
The update radius can't be set higher than 2 for technical reasons unfortunately. If you don't have any other questions / issues I will close this issue.

**Comment by splyfof** [comment]
How can i solve players being able to see fake ores then?

**Comment by DrexHD** [comment]
You could:
- Try to improve their network latency / server lag
- Use engine mode 1 (unfortunately less effective than 3)
- Try an [experimental build I just published](https://github.com/DrexHD/AntiXray/suites/13038224582/artifacts/706647304) that allows for higher update radius (performance hit is currently unknown)
