### ISSUE TITLE
Feature request:anti xray for dimensions from mods

### ISSUE THREAD

**Issue by ghost** [DrexHD/AntiXray#33]
I attempted to add some custom dimensions to the dimension list in config files but the server will crash on startup.
Could it possibly to make anti-xray feature become effective in modded dimensions?

**Comment by DrexHD** [comment]
It's possible to enable antixray in any dimension (also modded), please share the crash reports / logs, your config and the mod, whose dimension you are trying to enable antixray in.

**Comment by ghost** [comment]
> It's possible to enable antixray in any dimension (also modded), please share the crash reports / logs, your config and the mod, whose dimension you are trying to enable antixray in.

I tested with [twilight forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) and [blue skies](https://www.curseforge.com/minecraft/mc-mods/blue-skies) on Forge 1.19.2

I'm not sure if I messed sth up when configured antixray.
[antixray.txt](https://github.com/DrexHD/AntiXray/files/12047390/antixray.txt)
[latest.log](https://github.com/DrexHD/AntiXray/files/12047392/latest.log)
[crash-2023-07-14_19.34.25-fml.txt](https://github.com/DrexHD/AntiXray/files/12049929/crash-2023-07-14_19.34.25-fml.txt)

modlist:
anti-xray-1.3.0-Forge-1.19.2
structure_gel-1.19.2-2.7.2
twilightforest-1.19.2-4.2.1518-universal
blue_skies-1.19.2-1.3.20

**Comment by DrexHD** [comment]
Looks like it wasn't really possible to define configs for custom dimensions, because `:` is an invalid character in toml tables. In 1.3.1 you can now define them like this: `['blue_skies:everbright']`
