### ISSUE TITLE
Update to Java 17

### ISSUE THREAD

**Issue by Pendrag00n** [DrexHD/AntiXray#35]
When running on MohistMC 1.19.2 with Forge v43.2.14 I get: 
`[main/DEBUG] [mixin/]: antixray.mixins.json:LevelMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)`
It seems that the mod only supports Java 16. Is it possible to update to Java 17?

**Comment by DrexHD** [comment]
I have pushed a quick fix for this, however this does not cause any issues on the supported frameworks (fabric and forge), so I don't think this is worth an extra release (I don't support Hybrids like MohistMC, so you will have to get the release from GitHub actions or compile it yourself)!
