### ISSUE TITLE
Why do you need X-ray when the mod will allow you to do it like this?

### ISSUE THREAD

**Issue by DonorKrovi** [DrexHD/AntiXray#38]
![image](https://github.com/DrexHD/AntiXray/assets/60231586/b68faf41-605d-46dd-892f-274f1ccb3902)
![image](https://github.com/DrexHD/AntiXray/assets/60231586/1242be12-1bfc-4351-bbe6-33dd8053ce4c)

**Comment by DrexHD** [comment]
I am not sure what is happening in these screenshots, but this is not what the mod does. This is probably an incompatibility with another mod (if you have just Antixray installed this shouldn't happen). Pleas try to figure out which mod is incompatible with antixray using binary search.
