### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KBMC1364** [DrexHD/AntiXray#39]
Hi im having an issue where my server would crash at odd times with anti-xray-1.2.2-Forge-1.18.2.jar   
[crash-2023-12-21_16.00.25-server.txt](https://github.com/DrexHD/AntiXray/files/13765980/crash-2023-12-21_16.00.25-server.txt)

**Comment by DrexHD** [comment]
I assume this is a mod incompatibility (I haven't had any complaints like this yet). Please try to do binary search to find the incompatible mod. 
Also, you are running a fairly outdated version of Minecraft, unless this is also present in the current version, I likely wont fix it!
