### ISSUE TITLE
advanced-xray sees chests in the world.

### ISSUE THREAD

**Issue by jordanraytm** [DrexHD/AntiXray#47]
ore blocks are hidden well. advanced-xray and resource pack can't handle it, but it sees chests. the chest is registered in the config. what to do?
![image](https://github.com/DrexHD/AntiXray/assets/146493889/bb37d484-a7f0-429a-8d60-8dd9d9f05e11)
![image](https://github.com/DrexHD/AntiXray/assets/146493889/e8937380-4782-40a2-9377-406dfab4b2c8)

**Comment by arnokeesman** [comment]
for antixray to work the blocks need to be a couple blocks away from air, so when blocks are broken you see what you're supposed to, for a chest to work it has to be exposed to air, therefore you can't really antixray it

**Comment by jordanraytm** [comment]
What do I need to do ? can change the config. What do I need to change in the config to make it work?

**Comment by arnokeesman** [comment]
there's nothing you can change for this to work
it cant work with the concept of this mod
