### ISSUE TITLE
Create mod compatibility

### ISSUE THREAD

**Issue by muriplz** [DrexHD/AntiXray#50]
There is an issue when you make mining machines with `create:deployer` fakeplayers.

Issue log of the crash: https://pastebin.com/6ZLUB6r0

Thanks for the work you do! <3

**Comment by DrexHD** [comment]
Can you please check if the latest releases fixes your issue?

**Comment by Josuburga** [comment]
At least it doesn't work for me, even though I see that it's not the exact same crash.

[crash-2024-07-30_20.15.30-server.txt](https://github.com/user-attachments/files/16431953/crash-2024-07-30_20.15.30-server.txt)

**Comment by DrexHD** [comment]
@Josuburga that crash is related to #49, check https://github.com/DrexHD/AntiXray/issues/49#issuecomment-2243333893 for further info how to avoid it.

**Comment by Josuburga** [comment]
Ok yes, changing the fabric loader to 0.15.11 works. Thanks!

**Comment by muriplz** [comment]
i've been running it since the update launched and no issues so far!
