### ISSUE TITLE
Custom Dimensions not Covered by Mod

### ISSUE THREAD

**Issue by 15wileyr** [DrexHD/AntiXray#54]
Hello, I have added my own extra dimensions to my fabric server. I would like them to be covered by this mod but as it is they are not. Is there a way to add support for extra dimensions? like a list to add them or something?

**Comment by 15wileyr** [comment]
And thank you for the awesome mod I'm glad it exists, it works great otherwise :)

**Comment by 15wileyr** [comment]
Haha I missed it on the main page you can add custom dimensions as shown. 

You can use me as the example if someone else misses that note at the bottom as well. Out of curiosity why did you set nether to engine mode 1 ? It might be nice to note why somewhere. :) Thanks!!!!

![2024-08-24_21-27-50](https://github.com/user-attachments/assets/06bffd6f-7de3-43cb-a1e5-d3bbf1dbe2d3)

**Comment by DrexHD** [comment]
> Out of curiosity why did you set nether to engine mode 1 ?

The nether uses engine mode 1, because the most important ore, ancient debris, can't spawn next to air. So engine mode 1 will hide all ancient debris (if lavaObscures is also set to true) and have the benefit of not showing fake blocks when blocks are destroyed very fast or players have high ping.
