### ISSUE TITLE
Causing Random Crashes

### ISSUE THREAD

**Issue by Dominic54321** [DrexHD/AntiXray#56]
Crash report:
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2024-09-02 07:53:31
Description: Exception in server tick loop

java.lang.ClassCastException: class net.minecraft.class_2841$class_6563$Anonymous$6c59e6ac1bb246448cd6172a2137a887 cannot be cast to class net.minecraft.class_6880 (net.minecraft.class_2841$class_6563$Anonymous$6c59e6ac1bb246448cd6172a2137a887 and net.minecraft.class_6880 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1593948d)
	at net.minecraft.class_2378$1.method_10206(class_2378.java:186)
	at net.minecraft.class_2834.method_12290(class_2834.java:100)
	at net.minecraft.class_2841$class_6561.method_38306(class_2841.java:321)
	at net.minecraft.class_2841.method_12327(class_2841.java:275)
	at net.minecraft.class_2826.method_12260(class_2826.java:176)
	at net.minecraft.class_6603.method_38589(class_6603.java:80)
	at net.minecraft.class_6603.<init>(class_6603.java:42)
	at net.minecraft.class_2672.mixinextras$bridge$newclass_6603$15(class_2672.java)
	at net.minecraft.class_2672.wrapOperation$zfl000$antixray$setChunkPacketInfoArgument(class_2672.java:559)
	at net.minecraft.class_2672.<init>(class_2672.java:28)
	at net.minecraft.class_8608.method_52388(class_8608.java:88)
	at net.minecraft.class_8608.mixinextras$bridge$method_52388$14(class_8608.java)
	at net.minecraft.class_8608.wrapOperation$zgb000$antixray$setBatchStartPacketArgument(class_8608.java:556)
	at net.minecraft.class_8608.method_52386(class_8608.java:81)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1045)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 5.15.0-119-generic
	Java Version: 21.0.4, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 529030072 bytes (504 MiB) / 1904214016 bytes (1816 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: QEMU Virtual CPU version 2.5+
	Identifier: Intel64 Family 15 Model 107 Stepping 1
	Microarchitecture: Netburst
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Device
	Graphics card #0 vendor: Vendor (0x1234)
	Graphics card #0 VRAM (MiB): 16.00
	Graphics card #0 deviceId: 0x1111
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 10074.19
	Virtual memory used (MiB): 3374.65
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 48695.88, total: 64196.54
	Space in storage for workdir (MiB): available: 48695.88, total: 64196.54
	JVM Flags: 20 total; -Xms1024M -Xmx10240M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.30+1.21
		antixray: AntiXray 1.4.5
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		armorstands: Armor Stands 2.0.0
		audioplayer: AudioPlayer 1.21.1-1.10.3
			admiral: Admiral 0.4.5+1.21
		betterladdersmod: Better Ladders 0.0.3.1.21
		brrp_v1: Better Runtime Resource Pack (BRRP) v1 1.0.4
		chunky: Chunky 1.4.16
		cicada: CICADA 0.8.3+1.21-and-above
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		connectiblechains: Connectible Chains 2.4.2+1.21.1
		debugify: Debugify 1.21+1.0
		discord-mc-chat: Discord-MC-Chat 2.3.4
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.17.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.17.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.17.0
			com_google_code_gson_gson: gson 2.11.0
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			com_squareup_okhttp3_okhttp: okhttp 4.12.0
			com_squareup_okio_okio-jvm: okio-jvm 3.6.0
			discord-mc-chat-1_21: Discord-MC-Chat 2.3.4
			net_dv8tion_jda: JDA 5.0.0
			net_fellbaum_jemoji: jemoji 1.3.4
			net_sf_trove4j_core: core 3.1.0
			org_apache_commons_commons-collections4: commons-collections4 4.4
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_slf4j_slf4j-api: slf4j-api 2.0.13
		duckling: Duckling 5.0.1
			resourcefullib: Resourceful Lib 3.0.0
				com_teamresourceful_bytecodecs: bytecodecs 1.1.0
				com_teamresourceful_yabn: yabn 1.0.3
		evs: Enchanted Vertical Slabs 2.2
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.21-2.1.5+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta+fdrf.1+1.21
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta+fdrf.1+1.21
				porting_lib_asm: Porting Lib ASM 3.1.0-beta+fdrf.1+1.21
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta+fdrf.1+1.21
				porting_lib_common: Porting Lib Common 3.1.0-beta+fdrf.1+1.21
				porting_lib_entity: Porting Lib Entity 3.1.0-beta+fdrf.1+1.21
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta+fdrf.1+1.21
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta+fdrf.1+1.21
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta+fdrf.1+1.21
			porting_lib_config: Porting Lib Config 3.1.0-beta+fdrf.1+1.21
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta+fdrf.1+1.21
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta+fdrf.1+1.21
				porting_lib_core: Porting Lib Core 3.1.0-beta+fdrf.1+1.21
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta+fdrf.1+1.21
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta+fdrf.1+1.21
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta+fdrf.1+1.21
			porting_lib_loot: Porting Lib Loot 3.1.0-beta+fdrf.1+1.21
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta+fdrf.1+1.21
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta+fdrf.1+1.21
		ferritecore: FerriteCore 7.0.0
		geckolib: GeckoLib 4 4.5.8
		geophilic: Geophilic 3.1.1
		ichunutil: iChunUtil 1.0.0
		image2map: Image2Map 0.7.1+1.21
			map-canvas-api: Map Canvas API 0.4.1+1.21
			sgui: sgui 1.6.0+1.21
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lavender: Lavender 0.1.12+1.21
			lavender-md: lavender-md 0.1.1+1.21
		lithium: Lithium 0.13.0
		mcwfurnitures: Macaw's Furniture 3.3.0
		minecraft: Minecraft 1.21
		mns: Moog's Nether Structures 1.0.2-1.21-fabric
		modernfix: ModernFix 5.19.1+mc1.21
		monolib: MonoLib 1.3.0
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.3
		mr_immersive_structures: Immersive structures 2.2.0
		mr_lithosphere: Lithosphere 1.2
		mr_players_dropheads: Players Drop Heads 48.2
		mr_sleep: Sleep 1-v.2.7.3
		mr_true_ending: True Ending: Ender Dragon Overhaul 1-v1.1.2b
		no-enderman-grief: no-enderman-grief 1.1.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		noportals: No Portals 1.1.3
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
				packet_tweaker: Packet Tweaker 0.5.1+24w03b
		nullscape: Nullscape 1.2.7
		oth3r-sit: Sit! 1.1.9+1.21-1.21.1
		owo: oωo 0.12.11+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		spark: spark 1.10.97
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		timeoutout: TimeOut Out 1.0.4+1.20.2
		toggleableitemframes: Toggleable Item Frames 5.0.0-1.21.1
		trickster: Trickster 2.0.0-alpha.26
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
			lavender-md-owo-ui: lavender-md-owo-ui 0.1.2+1.21
		voicechat: Simple Voice Chat 1.21.1-2.5.20
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Server Running: true
	Player Count: 2 / 20; [class_3222['JT_5768364'/77961, l='ServerLevel[world]', x=-868.61, y=142.17, z=4832.16], class_3222['MishaNecron'/32429, l='ServerLevel[world]', x=-2281.80, y=58.00, z=53.34]]
	Active Data Packs: vanilla, fabric, accessories, audioplayer, connectiblechains, duckling, evs, fabric-convention-tags-v2, farmersdelight, geophilic, mcwfurnitures (incompatible), mns (incompatible), mr_dungeons_andtaverns, mr_immersive_structures, mr_lithosphere (incompatible), mr_players_dropheads, mr_sleep, mr_true_ending, noportals, nullscape, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, server_translations_api, trickster
	Available Data Packs: accessories, audioplayer, bundle, connectiblechains, duckling, evs, fabric, fabric-convention-tags-v2, farmersdelight, geophilic, mcwfurnitures (incompatible), mns (incompatible), mr_dungeons_andtaverns, mr_immersive_structures, mr_lithosphere (incompatible), mr_players_dropheads, mr_sleep, mr_true_ending, noportals, nullscape, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, server_translations_api, trade_rebalance, trickster, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -3550532486063793284
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	
	
Server Version: 1.21 Fabric
Mod Version: 1.4.5+1.21

Config file:

# Default configuration file for Fabric AntiXray mod by DrexHD

# Default values
enabled = false

# World specific values
[overworld]
enabled = true
engineMode = 3
maxBlockHeight = 256
updateRadius = 2
lavaObscures = false
hiddenBlocks = ["#c:ores", "raw_copper_block", "raw_iron_block", "raw_gold_block"]
replacementBlocks = ["stone", "deepslate", "andesite", "calcite", "diorite", "dirt", "granite", "gravel", "sand", "tuff", "mossy_cobblestone", "obsidian", "clay", "infested_stone", "amethyst_block", "budding_amethyst", "chest"]

[the_nether]
enabled = true
engineMode = 3
maxBlockHeight = 128
updateRadius = 2
lavaObscures = true
hiddenBlocks = ["ancient_debris", "nether_quartz_ore", "nether_gold_ore", "gold_block", "gilded_blackstone"]

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Dominic54321** [comment]
Gets blocked by AV, how am I supposed to use it anyways? Have docs?

**Comment by DrexHD** [comment]
That was likely a spam comment, don't trust them.
This issue seems to be the same as #55.
