### ISSUE TITLE
Server Crashing. Is this related to Engine Mode?

### ISSUE THREAD

**Issue by 15wileyr** [DrexHD/AntiXray#58]
My Apex Hosted Minecraft Fabric Server is crashing, not sure why? It wasn't doing so before so I'm not really sure why it is now. Does this error make any sense? Trying to determine what is the cause/solution. If it needs more ram or something else.

I don't have any crazy mods, the server is crashing while the only online 3 Players are generating new chunks while exploring in the same direction.

I have removed Xray Mod and now no longer get crashes. Is this potentially a performance related thing? 

Crash Report
[https://drive.google.com/file/d/19N53cURs3o_pNTxFdJRgb-3h-8Zillnd/view?usp=sharing](url)

Config File:
[antixray.txt](https://github.com/user-attachments/files/17092887/antixray.txt)

**Comment by DrexHD** [comment]
Use the [latest version of antixray](https://modrinth.com/mod/anti-xray/version/1.4.6+1.21.1). This has already been fixed!
