### ISSUE TITLE
True Darkness Anti-Full-Bright

### ISSUE THREAD

**Issue by BobzBlue** [DrexHD/AntiXray#59]
An incredibly niche suggestion for anti-full-bright when a mod like True Darkness Refabricated is installed.

**Comment by BobzBlue** [comment]
I just realized that a shader like rethinking voxels lights things in the distance... so being less strict would be necessary for my use case. Of course mod detection is not necessary, it could just be a setting.

**Comment by DrexHD** [comment]
Anti fullbright is not possible to do server side!

**Comment by BobzBlue** [comment]
It's only applicable when a mod like true darkness is intended to be used. (Ignoring rethinking voxels) any block with a light level of zero is invisible, allowing the server to client block data to be switched just like AntiXray. Again, very very niche.
