### ISSUE TITLE
Particles Randomly Showing in World {Fabric 1.20.1 v1.4.6}

### ISSUE THREAD

**Issue by RiftSpatial** [DrexHD/AntiXray#60]
Pink particles randomly spawn in the world. (Usually in huge chunks underground). They went away after removing the mod.
I did test with just this mod and it did not have this issue, so I am aware that another mod must be involved.
Before I try to find the other mod I was wondering if you knew what might be causing this as it is very odd.
![2024-11-08_22 56 32](https://github.com/user-attachments/assets/9ea2062f-a00a-4caa-a614-3fbeead7d1cc)

**Comment by DrexHD** [comment]
This is likely caused by modded ores spawning particles. Antixray uses them to obfuscate xrayers sight. The default config include `c#ores`, which includes all ores. You can manually list ores instead to ensure the ores with particles are not used!
